### ISSUE TITLE
Probably CSS Bug

### ISSUE THREAD

**Issue by Vrtak-CZ** [dg/adminer-custom#12] opened 2015-02-09 11:30 UTC
![snimek obrazovky porizeny 2015-02-09 12 27 35](https://cloud.githubusercontent.com/assets/112567/6105429/50891cda-b057-11e4-905d-3d6720e56539.png)

Chrome 40.0.2214.111 - ArchLinux

**Comment by pavel-dohnal** [comment] 2015-02-13 11:52
I can confirm this bug on Ubuntu. Chrome since version 36

**Comment by dg** [comment] 2015-02-17 17:25
Probably related to https://github.com/erming/tabcomplete. I'll try to use last release.

**Comment by Aurielle** [comment] 2015-08-28 23:19
I'm experiencing the problem as well, though in a slightly different flavor. Duplicated textarea makes it impossible to click the submit button, but this can be resolved by resizing the bottom one using browser capabilities.

![](https://cyan.aurielle.cz/2015-08-29_01-18-14.png)

**Comment by enumag** [comment] 2015-09-13 11:14
@Aurielle As a hotfix I added this to my adminer.css:

```
`#content > form > p > div {
	display: block !important;
}
```

**Closed** 2015-09-14 13:16 UTC

**Comment by dg** [comment] 2015-09-14 13:37
PR https://github.com/erming/tabcomplete/pull/18

**Comment by enumag** [comment] 2015-09-14 14:16
@dg Thank you. There is still a bug on the SQL command page (at least in firefox). The two textareas overlap each other but resizing them by cursor doesn't work correctly (one is only resized horizontally).

**Comment by dg** [comment] 2015-09-14 15:04
Fixed

**Comment by enumag** [comment] 2015-09-14 15:14
@dg Not completely.

1) Try reducing the height of the textarea. The button below the textarea doesn't move until the resize is completed.
2) The triangle icon on the bootom right of the second textarea is visible during the drag (and not overlapped by the first textarea).

I think the second textarea should be hidden when resizing, although I'm not sure if it's possible.

**Comment by dg** [comment] 2015-09-14 15:42
I added an event for mouseover.
